#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-PackageHomePage: https://github.com/paxx12-snapmaker-u1/SnapmakerU1-Extended-Firmware
# SPDX-FileCopyrightText: Copyright (c) 2026 @paxx12

EXTENDED2_CFG="/oem/printer_data/config/extended/extended2.cfg"
DISABLE_RFID_READER="/oem/printer_data/config/extended/klipper/disable-rfid-reader.cfg"
DISABLE_RFID_READER_TWEAK="/usr/local/share/firmware-config/tweaks/klipper/disable-rfid-reader.cfg"

start() {
    RFID=$(/usr/local/bin/extended-config.py get "$EXTENDED2_CFG" components rfid snapmaker 2>/dev/null)
    case "$RFID" in
        snapmaker)
            rm -vf "$DISABLE_RFID_READER"
            ;;
        *)
            ln -sf "$DISABLE_RFID_READER_TWEAK" "$DISABLE_RFID_READER"
            ;;
    esac
}

case "$1" in
    start|restart|reload)
        start
        ;;
    stop)
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit $?
